export const SET_USER_INFO_OK = "SET_USER_INFO_OK";
export const SEARCH_SOCIAL_ACCOUNTS_OK = "SEARCH_SOCIAL_ACCOUNTS_OK";
export const LOGIN_USER_OK = "LOGIN_USER_OK";
export const LOGOUT_USER_OK = "LOGOUT_USER_OK";
export const TOGGLE_FAVOURITE_ACCOUNT_OK = "TOGGLE_FAVOURITE_ACCOUNT_OK";